# Generated by Django 6.0.5 on 2026-05-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=512)),
                ('pickup_location', models.CharField(max_length=512)),
                ('dropoff_location', models.CharField(max_length=512)),
                ('cycle_hours_used', models.FloatField()),
                ('result_json', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
